==439756== Memcheck, a memory error detector
==439756== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==439756== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==439756== Command: ./build/bin/test_mst_project
==439756== Parent PID: 439752
==439756== 
==439756== Thread 4:
==439756== Invalid read of size 4
==439756==    at 0x14A7BD: Proactor::workerThread() (Proactor.cpp:72)
==439756==    by 0x14CF90: void std::__invoke_impl<void, void (Proactor::*)(), Proactor*>(std::__invoke_memfun_deref, void (Proactor::*&&)(), Proactor*&&) (invoke.h:74)
==439756==    by 0x14CE88: std::__invoke_result<void (Proactor::*)(), Proactor*>::type std::__invoke<void (Proactor::*)(), Proactor*>(void (Proactor::*&&)(), Proactor*&&) (invoke.h:96)
==439756==    by 0x14CD68: void std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (std_thread.h:301)
==439756==    by 0x14CCD7: std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> >::operator()() (std_thread.h:308)
==439756==    by 0x14CC9F: std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> > >::_M_run() (std_thread.h:253)
==439756==    by 0x49E0C33: execute_native_thread_routine (thread.cc:104)
==439756==    by 0x4D3839C: start_thread (pthread_create.c:447)
==439756==    by 0x4DBD2A3: clone (clone.S:100)
==439756==  Address 0x4ede5f8 is 200 bytes inside a block of size 248 free'd
==439756==    at 0x48488DD: operator delete(void*, unsigned long) (vg_replace_malloc.c:1181)
==439756==    by 0x16B0C4: std::default_delete<Proactor>::operator()(Proactor*) const (unique_ptr.h:93)
==439756==    by 0x16AB45: std::unique_ptr<Proactor, std::default_delete<Proactor> >::~unique_ptr() (unique_ptr.h:398)
==439756==    by 0x16BA0B: ProactorTest::~ProactorTest() (proactor-test.cpp:10)
==439756==    by 0x16BA6D: ProactorTest_ThreadCleanup_Test::~ProactorTest_ThreadCleanup_Test() (proactor-test.cpp:96)
==439756==    by 0x16BA89: ProactorTest_ThreadCleanup_Test::~ProactorTest_ThreadCleanup_Test() (proactor-test.cpp:96)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C52ED: testing::TestInfo::Run() (gtest.cc:2865)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756==  Block was alloc'd at
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x16AA9D: std::__detail::_MakeUniq<Proactor>::__single_object std::make_unique<Proactor>() (unique_ptr.h:1076)
==439756==    by 0x16A5E3: ProactorTest::SetUp() (proactor-test.cpp:16)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C50F2: UnknownInlinedFun (gtest.cc:2708)
==439756==    by 0x48C50F2: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== 
==439756== HEAP SUMMARY:
==439756==     in use at exit: 1,032 bytes in 9 blocks
==439756==   total heap usage: 1,764 allocs, 1,755 frees, 328,784 bytes allocated
==439756== 
==439756== Thread 1:
==439756== 8 bytes in 1 blocks are definitely lost in loss record 1 of 7
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x14A5D9: Proactor::run(int, std::function<void (int)>) (Proactor.cpp:52)
==439756==    by 0x1688D2: ProactorTest_ThreadCleanup_Test::TestBody() (proactor-test.cpp:101)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== 16 bytes in 2 blocks are definitely lost in loss record 2 of 7
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x14A5D9: Proactor::run(int, std::function<void (int)>) (Proactor.cpp:52)
==439756==    by 0x168963: ProactorTest_ThreadCleanup_Test::TestBody() (proactor-test.cpp:107)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== 32 bytes in 1 blocks are still reachable in loss record 3 of 7
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x14AD7F: std::thread::thread<void (Proactor::*)(), Proactor*, void>(void (Proactor::*&&)(), Proactor*&&) (std_thread.h:173)
==439756==    by 0x14A610: Proactor::run(int, std::function<void (int)>) (Proactor.cpp:52)
==439756==    by 0x1688D2: ProactorTest_ThreadCleanup_Test::TestBody() (proactor-test.cpp:101)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== 64 bytes in 2 blocks are still reachable in loss record 4 of 7
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x14AD7F: std::thread::thread<void (Proactor::*)(), Proactor*, void>(void (Proactor::*&&)(), Proactor*&&) (std_thread.h:173)
==439756==    by 0x14A610: Proactor::run(int, std::function<void (int)>) (Proactor.cpp:52)
==439756==    by 0x168963: ProactorTest_ThreadCleanup_Test::TestBody() (proactor-test.cpp:107)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== 304 bytes in 1 blocks are possibly lost in loss record 5 of 7
==439756==    at 0x484BC13: calloc (vg_replace_malloc.c:1675)
==439756==    by 0x4011003: calloc (rtld-malloc.h:44)
==439756==    by 0x4011003: allocate_dtv (dl-tls.c:395)
==439756==    by 0x4011AE1: _dl_allocate_tls (dl-tls.c:664)
==439756==    by 0x4D38F14: allocate_stack (allocatestack.c:429)
==439756==    by 0x4D38F14: pthread_create@@GLIBC_2.34 (pthread_create.c:655)
==439756==    by 0x49E0D31: __gthread_create (gthr-default.h:676)
==439756==    by 0x49E0D31: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:172)
==439756==    by 0x145FA4: std::thread::thread<Pipeline::start()::{lambda()#1}, , void>(Pipeline::start()::{lambda()#1}&&) (std_thread.h:173)
==439756==    by 0x14572F: Pipeline::start() (Pipeline.cpp:76)
==439756==    by 0x158D56: PipelineTest_StartAndStop_Test::TestBody() (in /home/sibo/Desktop/Year_2_B/Maharahot_hafhala/need_to_do/mst_project/build/bin/test_mst_project)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756== 
==439756== 304 bytes in 1 blocks are possibly lost in loss record 6 of 7
==439756==    at 0x484BC13: calloc (vg_replace_malloc.c:1675)
==439756==    by 0x4011003: calloc (rtld-malloc.h:44)
==439756==    by 0x4011003: allocate_dtv (dl-tls.c:395)
==439756==    by 0x4011AE1: _dl_allocate_tls (dl-tls.c:664)
==439756==    by 0x4D38F14: allocate_stack (allocatestack.c:429)
==439756==    by 0x4D38F14: pthread_create@@GLIBC_2.34 (pthread_create.c:655)
==439756==    by 0x49E0D31: __gthread_create (gthr-default.h:676)
==439756==    by 0x49E0D31: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:172)
==439756==    by 0x169A5A: std::thread::thread<ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}, , void>(ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}&&) (std_thread.h:173)
==439756==    by 0x168CDE: construct<std::thread, ProactorTest_MultipleConnections_Test::TestBody()::<lambda()> > (new_allocator.h:191)
==439756==    by 0x168CDE: construct<std::thread, ProactorTest_MultipleConnections_Test::TestBody()::<lambda()> > (alloc_traits.h:534)
==439756==    by 0x168CDE: std::thread& std::vector<std::thread, std::allocator<std::thread> >::emplace_back<ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}>(ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}&&) (vector.tcc:117)
==439756==    by 0x168607: ProactorTest_MultipleConnections_Test::TestBody() (proactor-test.cpp:79)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756== 
==439756== 304 bytes in 1 blocks are possibly lost in loss record 7 of 7
==439756==    at 0x484BC13: calloc (vg_replace_malloc.c:1675)
==439756==    by 0x4011003: calloc (rtld-malloc.h:44)
==439756==    by 0x4011003: allocate_dtv (dl-tls.c:395)
==439756==    by 0x4011AE1: _dl_allocate_tls (dl-tls.c:664)
==439756==    by 0x4D38F14: allocate_stack (allocatestack.c:429)
==439756==    by 0x4D38F14: pthread_create@@GLIBC_2.34 (pthread_create.c:655)
==439756==    by 0x49E0D31: __gthread_create (gthr-default.h:676)
==439756==    by 0x49E0D31: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (thread.cc:172)
==439756==    by 0x169A5A: std::thread::thread<ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}, , void>(ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}&&) (std_thread.h:173)
==439756==    by 0x169218: construct<std::thread, ProactorTest_MultipleConnections_Test::TestBody()::<lambda()> > (new_allocator.h:191)
==439756==    by 0x169218: construct<std::thread, ProactorTest_MultipleConnections_Test::TestBody()::<lambda()> > (alloc_traits.h:534)
==439756==    by 0x169218: void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_append<ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}>(ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}&&) (vector.tcc:634)
==439756==    by 0x168D32: std::thread& std::vector<std::thread, std::allocator<std::thread> >::emplace_back<ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}>(ProactorTest_MultipleConnections_Test::TestBody()::{lambda()#1}&&) (vector.tcc:123)
==439756==    by 0x168607: ProactorTest_MultipleConnections_Test::TestBody() (proactor-test.cpp:79)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C516F: UnknownInlinedFun (gtest.cc:2713)
==439756==    by 0x48C516F: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756== 
==439756== LEAK SUMMARY:
==439756==    definitely lost: 24 bytes in 3 blocks
==439756==    indirectly lost: 0 bytes in 0 blocks
==439756==      possibly lost: 912 bytes in 3 blocks
==439756==    still reachable: 96 bytes in 3 blocks
==439756==         suppressed: 0 bytes in 0 blocks
==439756== 
==439756== ERROR SUMMARY: 7 errors from 6 contexts (suppressed: 0 from 0)
==439756== 
==439756== 2 errors in context 1 of 6:
==439756== Thread 4:
==439756== Invalid read of size 4
==439756==    at 0x14A7BD: Proactor::workerThread() (Proactor.cpp:72)
==439756==    by 0x14CF90: void std::__invoke_impl<void, void (Proactor::*)(), Proactor*>(std::__invoke_memfun_deref, void (Proactor::*&&)(), Proactor*&&) (invoke.h:74)
==439756==    by 0x14CE88: std::__invoke_result<void (Proactor::*)(), Proactor*>::type std::__invoke<void (Proactor::*)(), Proactor*>(void (Proactor::*&&)(), Proactor*&&) (invoke.h:96)
==439756==    by 0x14CD68: void std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (std_thread.h:301)
==439756==    by 0x14CCD7: std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> >::operator()() (std_thread.h:308)
==439756==    by 0x14CC9F: std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Proactor::*)(), Proactor*> > >::_M_run() (std_thread.h:253)
==439756==    by 0x49E0C33: execute_native_thread_routine (thread.cc:104)
==439756==    by 0x4D3839C: start_thread (pthread_create.c:447)
==439756==    by 0x4DBD2A3: clone (clone.S:100)
==439756==  Address 0x4ede5f8 is 200 bytes inside a block of size 248 free'd
==439756==    at 0x48488DD: operator delete(void*, unsigned long) (vg_replace_malloc.c:1181)
==439756==    by 0x16B0C4: std::default_delete<Proactor>::operator()(Proactor*) const (unique_ptr.h:93)
==439756==    by 0x16AB45: std::unique_ptr<Proactor, std::default_delete<Proactor> >::~unique_ptr() (unique_ptr.h:398)
==439756==    by 0x16BA0B: ProactorTest::~ProactorTest() (proactor-test.cpp:10)
==439756==    by 0x16BA6D: ProactorTest_ThreadCleanup_Test::~ProactorTest_ThreadCleanup_Test() (proactor-test.cpp:96)
==439756==    by 0x16BA89: ProactorTest_ThreadCleanup_Test::~ProactorTest_ThreadCleanup_Test() (proactor-test.cpp:96)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C52ED: testing::TestInfo::Run() (gtest.cc:2865)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756==  Block was alloc'd at
==439756==    at 0x4844F93: operator new(unsigned long) (vg_replace_malloc.c:487)
==439756==    by 0x16AA9D: std::__detail::_MakeUniq<Proactor>::__single_object std::make_unique<Proactor>() (unique_ptr.h:1076)
==439756==    by 0x16A5E3: ProactorTest::SetUp() (proactor-test.cpp:16)
==439756==    by 0x48D98E9: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D98E9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [clone .constprop.0] (gtest.cc:2674)
==439756==    by 0x48C50F2: UnknownInlinedFun (gtest.cc:2708)
==439756==    by 0x48C50F2: testing::Test::Run() (gtest.cc:2703)
==439756==    by 0x48C536E: testing::TestInfo::Run() (gtest.cc:2859)
==439756==    by 0x48C5553: UnknownInlinedFun (gtest.cc:3037)
==439756==    by 0x48C5553: testing::TestSuite::Run() (gtest.cc:2991)
==439756==    by 0x48D1708: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5967)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2638)
==439756==    by 0x48D1D78: UnknownInlinedFun (gtest.cc:2674)
==439756==    by 0x48D1D78: testing::UnitTest::Run() (gtest.cc:5546)
==439756==    by 0x48FB069: UnknownInlinedFun (gtest.h:2334)
==439756==    by 0x48FB069: main (gtest_main.cc:64)
==439756== 
==439756== ERROR SUMMARY: 7 errors from 6 contexts (suppressed: 0 from 0)
